version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: yosep-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: myweb
    ports:
      - "3307:3306"
    volumes:
      - ./db_data:/var/lib/mysql

  myapp:
    build: .
    container_name: yosep-server
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/myweb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234